name: test_project
description: "just smth"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  retrofit: ^4.1.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.4
  get_it: ^7.2.0
  equatable: ^2.0.5
  path_provider: ^2.1.2
  awesome_dio_interceptor: ^1.2.0
  auto_route: ^7.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true